catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project QuantumMonteCarloU50
set_top QuantumMonteCarloU50
# v++ -g, -D, -I, --advanced.prop kernel.QuantumMonteCarloU50.kernel_flags
add_files "/home/edci/workspace/SQA_kernels/src/qmc.cpp" -cflags " -I /home/edci/workspace/SQA_kernels/src "
open_solution -flow_target vitis solution
set_part xcu50-fsvh2104-2-e
create_clock -period 300.000000MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname QuantumMonteCarloU50
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
