// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module QuantumMonteCarloU50_QuantumMonteCarloU50_Pipeline_SHIFT_JCOUP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        JcoupLocal_0_0_address0,
        JcoupLocal_0_0_ce0,
        JcoupLocal_0_0_q0,
        JcoupLocal_0_1_address0,
        JcoupLocal_0_1_ce0,
        JcoupLocal_0_1_q0,
        JcoupLocal_0_2_address0,
        JcoupLocal_0_2_ce0,
        JcoupLocal_0_2_q0,
        JcoupLocal_0_3_address0,
        JcoupLocal_0_3_ce0,
        JcoupLocal_0_3_q0,
        JcoupLocal_0_4_address0,
        JcoupLocal_0_4_ce0,
        JcoupLocal_0_4_q0,
        JcoupLocal_0_5_address0,
        JcoupLocal_0_5_ce0,
        JcoupLocal_0_5_q0,
        JcoupLocal_0_6_address0,
        JcoupLocal_0_6_ce0,
        JcoupLocal_0_6_q0,
        JcoupLocal_0_7_address0,
        JcoupLocal_0_7_ce0,
        JcoupLocal_0_7_q0,
        JcoupLocal_0_8_address0,
        JcoupLocal_0_8_ce0,
        JcoupLocal_0_8_q0,
        JcoupLocal_0_9_address0,
        JcoupLocal_0_9_ce0,
        JcoupLocal_0_9_q0,
        JcoupLocal_0_10_address0,
        JcoupLocal_0_10_ce0,
        JcoupLocal_0_10_q0,
        JcoupLocal_0_11_address0,
        JcoupLocal_0_11_ce0,
        JcoupLocal_0_11_q0,
        JcoupLocal_0_12_address0,
        JcoupLocal_0_12_ce0,
        JcoupLocal_0_12_q0,
        JcoupLocal_0_13_address0,
        JcoupLocal_0_13_ce0,
        JcoupLocal_0_13_q0,
        JcoupLocal_0_14_address0,
        JcoupLocal_0_14_ce0,
        JcoupLocal_0_14_q0,
        JcoupLocal_0_15_address0,
        JcoupLocal_0_15_ce0,
        JcoupLocal_0_15_q0,
        JcoupLocal_1_0_address0,
        JcoupLocal_1_0_ce0,
        JcoupLocal_1_0_we0,
        JcoupLocal_1_0_d0,
        JcoupLocal_1_0_q0,
        JcoupLocal_1_1_address0,
        JcoupLocal_1_1_ce0,
        JcoupLocal_1_1_we0,
        JcoupLocal_1_1_d0,
        JcoupLocal_1_1_q0,
        JcoupLocal_1_2_address0,
        JcoupLocal_1_2_ce0,
        JcoupLocal_1_2_we0,
        JcoupLocal_1_2_d0,
        JcoupLocal_1_2_q0,
        JcoupLocal_1_3_address0,
        JcoupLocal_1_3_ce0,
        JcoupLocal_1_3_we0,
        JcoupLocal_1_3_d0,
        JcoupLocal_1_3_q0,
        JcoupLocal_1_4_address0,
        JcoupLocal_1_4_ce0,
        JcoupLocal_1_4_we0,
        JcoupLocal_1_4_d0,
        JcoupLocal_1_4_q0,
        JcoupLocal_1_5_address0,
        JcoupLocal_1_5_ce0,
        JcoupLocal_1_5_we0,
        JcoupLocal_1_5_d0,
        JcoupLocal_1_5_q0,
        JcoupLocal_1_6_address0,
        JcoupLocal_1_6_ce0,
        JcoupLocal_1_6_we0,
        JcoupLocal_1_6_d0,
        JcoupLocal_1_6_q0,
        JcoupLocal_1_7_address0,
        JcoupLocal_1_7_ce0,
        JcoupLocal_1_7_we0,
        JcoupLocal_1_7_d0,
        JcoupLocal_1_7_q0,
        JcoupLocal_1_8_address0,
        JcoupLocal_1_8_ce0,
        JcoupLocal_1_8_we0,
        JcoupLocal_1_8_d0,
        JcoupLocal_1_8_q0,
        JcoupLocal_1_9_address0,
        JcoupLocal_1_9_ce0,
        JcoupLocal_1_9_we0,
        JcoupLocal_1_9_d0,
        JcoupLocal_1_9_q0,
        JcoupLocal_1_10_address0,
        JcoupLocal_1_10_ce0,
        JcoupLocal_1_10_we0,
        JcoupLocal_1_10_d0,
        JcoupLocal_1_10_q0,
        JcoupLocal_1_11_address0,
        JcoupLocal_1_11_ce0,
        JcoupLocal_1_11_we0,
        JcoupLocal_1_11_d0,
        JcoupLocal_1_11_q0,
        JcoupLocal_1_12_address0,
        JcoupLocal_1_12_ce0,
        JcoupLocal_1_12_we0,
        JcoupLocal_1_12_d0,
        JcoupLocal_1_12_q0,
        JcoupLocal_1_13_address0,
        JcoupLocal_1_13_ce0,
        JcoupLocal_1_13_we0,
        JcoupLocal_1_13_d0,
        JcoupLocal_1_13_q0,
        JcoupLocal_1_14_address0,
        JcoupLocal_1_14_ce0,
        JcoupLocal_1_14_we0,
        JcoupLocal_1_14_d0,
        JcoupLocal_1_14_q0,
        JcoupLocal_1_15_address0,
        JcoupLocal_1_15_ce0,
        JcoupLocal_1_15_we0,
        JcoupLocal_1_15_d0,
        JcoupLocal_1_15_q0,
        JcoupLocal_2_0_address0,
        JcoupLocal_2_0_ce0,
        JcoupLocal_2_0_we0,
        JcoupLocal_2_0_d0,
        JcoupLocal_2_0_q0,
        JcoupLocal_2_1_address0,
        JcoupLocal_2_1_ce0,
        JcoupLocal_2_1_we0,
        JcoupLocal_2_1_d0,
        JcoupLocal_2_1_q0,
        JcoupLocal_2_2_address0,
        JcoupLocal_2_2_ce0,
        JcoupLocal_2_2_we0,
        JcoupLocal_2_2_d0,
        JcoupLocal_2_2_q0,
        JcoupLocal_2_3_address0,
        JcoupLocal_2_3_ce0,
        JcoupLocal_2_3_we0,
        JcoupLocal_2_3_d0,
        JcoupLocal_2_3_q0,
        JcoupLocal_2_4_address0,
        JcoupLocal_2_4_ce0,
        JcoupLocal_2_4_we0,
        JcoupLocal_2_4_d0,
        JcoupLocal_2_4_q0,
        JcoupLocal_2_5_address0,
        JcoupLocal_2_5_ce0,
        JcoupLocal_2_5_we0,
        JcoupLocal_2_5_d0,
        JcoupLocal_2_5_q0,
        JcoupLocal_2_6_address0,
        JcoupLocal_2_6_ce0,
        JcoupLocal_2_6_we0,
        JcoupLocal_2_6_d0,
        JcoupLocal_2_6_q0,
        JcoupLocal_2_7_address0,
        JcoupLocal_2_7_ce0,
        JcoupLocal_2_7_we0,
        JcoupLocal_2_7_d0,
        JcoupLocal_2_7_q0,
        JcoupLocal_2_8_address0,
        JcoupLocal_2_8_ce0,
        JcoupLocal_2_8_we0,
        JcoupLocal_2_8_d0,
        JcoupLocal_2_8_q0,
        JcoupLocal_2_9_address0,
        JcoupLocal_2_9_ce0,
        JcoupLocal_2_9_we0,
        JcoupLocal_2_9_d0,
        JcoupLocal_2_9_q0,
        JcoupLocal_2_10_address0,
        JcoupLocal_2_10_ce0,
        JcoupLocal_2_10_we0,
        JcoupLocal_2_10_d0,
        JcoupLocal_2_10_q0,
        JcoupLocal_2_11_address0,
        JcoupLocal_2_11_ce0,
        JcoupLocal_2_11_we0,
        JcoupLocal_2_11_d0,
        JcoupLocal_2_11_q0,
        JcoupLocal_2_12_address0,
        JcoupLocal_2_12_ce0,
        JcoupLocal_2_12_we0,
        JcoupLocal_2_12_d0,
        JcoupLocal_2_12_q0,
        JcoupLocal_2_13_address0,
        JcoupLocal_2_13_ce0,
        JcoupLocal_2_13_we0,
        JcoupLocal_2_13_d0,
        JcoupLocal_2_13_q0,
        JcoupLocal_2_14_address0,
        JcoupLocal_2_14_ce0,
        JcoupLocal_2_14_we0,
        JcoupLocal_2_14_d0,
        JcoupLocal_2_14_q0,
        JcoupLocal_2_15_address0,
        JcoupLocal_2_15_ce0,
        JcoupLocal_2_15_we0,
        JcoupLocal_2_15_d0,
        JcoupLocal_2_15_q0,
        JcoupLocal_3_0_address0,
        JcoupLocal_3_0_ce0,
        JcoupLocal_3_0_we0,
        JcoupLocal_3_0_d0,
        JcoupLocal_3_1_address0,
        JcoupLocal_3_1_ce0,
        JcoupLocal_3_1_we0,
        JcoupLocal_3_1_d0,
        JcoupLocal_3_2_address0,
        JcoupLocal_3_2_ce0,
        JcoupLocal_3_2_we0,
        JcoupLocal_3_2_d0,
        JcoupLocal_3_3_address0,
        JcoupLocal_3_3_ce0,
        JcoupLocal_3_3_we0,
        JcoupLocal_3_3_d0,
        JcoupLocal_3_4_address0,
        JcoupLocal_3_4_ce0,
        JcoupLocal_3_4_we0,
        JcoupLocal_3_4_d0,
        JcoupLocal_3_5_address0,
        JcoupLocal_3_5_ce0,
        JcoupLocal_3_5_we0,
        JcoupLocal_3_5_d0,
        JcoupLocal_3_6_address0,
        JcoupLocal_3_6_ce0,
        JcoupLocal_3_6_we0,
        JcoupLocal_3_6_d0,
        JcoupLocal_3_7_address0,
        JcoupLocal_3_7_ce0,
        JcoupLocal_3_7_we0,
        JcoupLocal_3_7_d0,
        JcoupLocal_3_8_address0,
        JcoupLocal_3_8_ce0,
        JcoupLocal_3_8_we0,
        JcoupLocal_3_8_d0,
        JcoupLocal_3_9_address0,
        JcoupLocal_3_9_ce0,
        JcoupLocal_3_9_we0,
        JcoupLocal_3_9_d0,
        JcoupLocal_3_10_address0,
        JcoupLocal_3_10_ce0,
        JcoupLocal_3_10_we0,
        JcoupLocal_3_10_d0,
        JcoupLocal_3_11_address0,
        JcoupLocal_3_11_ce0,
        JcoupLocal_3_11_we0,
        JcoupLocal_3_11_d0,
        JcoupLocal_3_12_address0,
        JcoupLocal_3_12_ce0,
        JcoupLocal_3_12_we0,
        JcoupLocal_3_12_d0,
        JcoupLocal_3_13_address0,
        JcoupLocal_3_13_ce0,
        JcoupLocal_3_13_we0,
        JcoupLocal_3_13_d0,
        JcoupLocal_3_14_address0,
        JcoupLocal_3_14_ce0,
        JcoupLocal_3_14_we0,
        JcoupLocal_3_14_d0,
        JcoupLocal_3_15_address0,
        JcoupLocal_3_15_ce0,
        JcoupLocal_3_15_we0,
        JcoupLocal_3_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] JcoupLocal_0_0_address0;
output   JcoupLocal_0_0_ce0;
input  [511:0] JcoupLocal_0_0_q0;
output  [3:0] JcoupLocal_0_1_address0;
output   JcoupLocal_0_1_ce0;
input  [511:0] JcoupLocal_0_1_q0;
output  [3:0] JcoupLocal_0_2_address0;
output   JcoupLocal_0_2_ce0;
input  [511:0] JcoupLocal_0_2_q0;
output  [3:0] JcoupLocal_0_3_address0;
output   JcoupLocal_0_3_ce0;
input  [511:0] JcoupLocal_0_3_q0;
output  [3:0] JcoupLocal_0_4_address0;
output   JcoupLocal_0_4_ce0;
input  [511:0] JcoupLocal_0_4_q0;
output  [3:0] JcoupLocal_0_5_address0;
output   JcoupLocal_0_5_ce0;
input  [511:0] JcoupLocal_0_5_q0;
output  [3:0] JcoupLocal_0_6_address0;
output   JcoupLocal_0_6_ce0;
input  [511:0] JcoupLocal_0_6_q0;
output  [3:0] JcoupLocal_0_7_address0;
output   JcoupLocal_0_7_ce0;
input  [511:0] JcoupLocal_0_7_q0;
output  [3:0] JcoupLocal_0_8_address0;
output   JcoupLocal_0_8_ce0;
input  [511:0] JcoupLocal_0_8_q0;
output  [3:0] JcoupLocal_0_9_address0;
output   JcoupLocal_0_9_ce0;
input  [511:0] JcoupLocal_0_9_q0;
output  [3:0] JcoupLocal_0_10_address0;
output   JcoupLocal_0_10_ce0;
input  [511:0] JcoupLocal_0_10_q0;
output  [3:0] JcoupLocal_0_11_address0;
output   JcoupLocal_0_11_ce0;
input  [511:0] JcoupLocal_0_11_q0;
output  [3:0] JcoupLocal_0_12_address0;
output   JcoupLocal_0_12_ce0;
input  [511:0] JcoupLocal_0_12_q0;
output  [3:0] JcoupLocal_0_13_address0;
output   JcoupLocal_0_13_ce0;
input  [511:0] JcoupLocal_0_13_q0;
output  [3:0] JcoupLocal_0_14_address0;
output   JcoupLocal_0_14_ce0;
input  [511:0] JcoupLocal_0_14_q0;
output  [3:0] JcoupLocal_0_15_address0;
output   JcoupLocal_0_15_ce0;
input  [511:0] JcoupLocal_0_15_q0;
output  [3:0] JcoupLocal_1_0_address0;
output   JcoupLocal_1_0_ce0;
output   JcoupLocal_1_0_we0;
output  [511:0] JcoupLocal_1_0_d0;
input  [511:0] JcoupLocal_1_0_q0;
output  [3:0] JcoupLocal_1_1_address0;
output   JcoupLocal_1_1_ce0;
output   JcoupLocal_1_1_we0;
output  [511:0] JcoupLocal_1_1_d0;
input  [511:0] JcoupLocal_1_1_q0;
output  [3:0] JcoupLocal_1_2_address0;
output   JcoupLocal_1_2_ce0;
output   JcoupLocal_1_2_we0;
output  [511:0] JcoupLocal_1_2_d0;
input  [511:0] JcoupLocal_1_2_q0;
output  [3:0] JcoupLocal_1_3_address0;
output   JcoupLocal_1_3_ce0;
output   JcoupLocal_1_3_we0;
output  [511:0] JcoupLocal_1_3_d0;
input  [511:0] JcoupLocal_1_3_q0;
output  [3:0] JcoupLocal_1_4_address0;
output   JcoupLocal_1_4_ce0;
output   JcoupLocal_1_4_we0;
output  [511:0] JcoupLocal_1_4_d0;
input  [511:0] JcoupLocal_1_4_q0;
output  [3:0] JcoupLocal_1_5_address0;
output   JcoupLocal_1_5_ce0;
output   JcoupLocal_1_5_we0;
output  [511:0] JcoupLocal_1_5_d0;
input  [511:0] JcoupLocal_1_5_q0;
output  [3:0] JcoupLocal_1_6_address0;
output   JcoupLocal_1_6_ce0;
output   JcoupLocal_1_6_we0;
output  [511:0] JcoupLocal_1_6_d0;
input  [511:0] JcoupLocal_1_6_q0;
output  [3:0] JcoupLocal_1_7_address0;
output   JcoupLocal_1_7_ce0;
output   JcoupLocal_1_7_we0;
output  [511:0] JcoupLocal_1_7_d0;
input  [511:0] JcoupLocal_1_7_q0;
output  [3:0] JcoupLocal_1_8_address0;
output   JcoupLocal_1_8_ce0;
output   JcoupLocal_1_8_we0;
output  [511:0] JcoupLocal_1_8_d0;
input  [511:0] JcoupLocal_1_8_q0;
output  [3:0] JcoupLocal_1_9_address0;
output   JcoupLocal_1_9_ce0;
output   JcoupLocal_1_9_we0;
output  [511:0] JcoupLocal_1_9_d0;
input  [511:0] JcoupLocal_1_9_q0;
output  [3:0] JcoupLocal_1_10_address0;
output   JcoupLocal_1_10_ce0;
output   JcoupLocal_1_10_we0;
output  [511:0] JcoupLocal_1_10_d0;
input  [511:0] JcoupLocal_1_10_q0;
output  [3:0] JcoupLocal_1_11_address0;
output   JcoupLocal_1_11_ce0;
output   JcoupLocal_1_11_we0;
output  [511:0] JcoupLocal_1_11_d0;
input  [511:0] JcoupLocal_1_11_q0;
output  [3:0] JcoupLocal_1_12_address0;
output   JcoupLocal_1_12_ce0;
output   JcoupLocal_1_12_we0;
output  [511:0] JcoupLocal_1_12_d0;
input  [511:0] JcoupLocal_1_12_q0;
output  [3:0] JcoupLocal_1_13_address0;
output   JcoupLocal_1_13_ce0;
output   JcoupLocal_1_13_we0;
output  [511:0] JcoupLocal_1_13_d0;
input  [511:0] JcoupLocal_1_13_q0;
output  [3:0] JcoupLocal_1_14_address0;
output   JcoupLocal_1_14_ce0;
output   JcoupLocal_1_14_we0;
output  [511:0] JcoupLocal_1_14_d0;
input  [511:0] JcoupLocal_1_14_q0;
output  [3:0] JcoupLocal_1_15_address0;
output   JcoupLocal_1_15_ce0;
output   JcoupLocal_1_15_we0;
output  [511:0] JcoupLocal_1_15_d0;
input  [511:0] JcoupLocal_1_15_q0;
output  [3:0] JcoupLocal_2_0_address0;
output   JcoupLocal_2_0_ce0;
output   JcoupLocal_2_0_we0;
output  [511:0] JcoupLocal_2_0_d0;
input  [511:0] JcoupLocal_2_0_q0;
output  [3:0] JcoupLocal_2_1_address0;
output   JcoupLocal_2_1_ce0;
output   JcoupLocal_2_1_we0;
output  [511:0] JcoupLocal_2_1_d0;
input  [511:0] JcoupLocal_2_1_q0;
output  [3:0] JcoupLocal_2_2_address0;
output   JcoupLocal_2_2_ce0;
output   JcoupLocal_2_2_we0;
output  [511:0] JcoupLocal_2_2_d0;
input  [511:0] JcoupLocal_2_2_q0;
output  [3:0] JcoupLocal_2_3_address0;
output   JcoupLocal_2_3_ce0;
output   JcoupLocal_2_3_we0;
output  [511:0] JcoupLocal_2_3_d0;
input  [511:0] JcoupLocal_2_3_q0;
output  [3:0] JcoupLocal_2_4_address0;
output   JcoupLocal_2_4_ce0;
output   JcoupLocal_2_4_we0;
output  [511:0] JcoupLocal_2_4_d0;
input  [511:0] JcoupLocal_2_4_q0;
output  [3:0] JcoupLocal_2_5_address0;
output   JcoupLocal_2_5_ce0;
output   JcoupLocal_2_5_we0;
output  [511:0] JcoupLocal_2_5_d0;
input  [511:0] JcoupLocal_2_5_q0;
output  [3:0] JcoupLocal_2_6_address0;
output   JcoupLocal_2_6_ce0;
output   JcoupLocal_2_6_we0;
output  [511:0] JcoupLocal_2_6_d0;
input  [511:0] JcoupLocal_2_6_q0;
output  [3:0] JcoupLocal_2_7_address0;
output   JcoupLocal_2_7_ce0;
output   JcoupLocal_2_7_we0;
output  [511:0] JcoupLocal_2_7_d0;
input  [511:0] JcoupLocal_2_7_q0;
output  [3:0] JcoupLocal_2_8_address0;
output   JcoupLocal_2_8_ce0;
output   JcoupLocal_2_8_we0;
output  [511:0] JcoupLocal_2_8_d0;
input  [511:0] JcoupLocal_2_8_q0;
output  [3:0] JcoupLocal_2_9_address0;
output   JcoupLocal_2_9_ce0;
output   JcoupLocal_2_9_we0;
output  [511:0] JcoupLocal_2_9_d0;
input  [511:0] JcoupLocal_2_9_q0;
output  [3:0] JcoupLocal_2_10_address0;
output   JcoupLocal_2_10_ce0;
output   JcoupLocal_2_10_we0;
output  [511:0] JcoupLocal_2_10_d0;
input  [511:0] JcoupLocal_2_10_q0;
output  [3:0] JcoupLocal_2_11_address0;
output   JcoupLocal_2_11_ce0;
output   JcoupLocal_2_11_we0;
output  [511:0] JcoupLocal_2_11_d0;
input  [511:0] JcoupLocal_2_11_q0;
output  [3:0] JcoupLocal_2_12_address0;
output   JcoupLocal_2_12_ce0;
output   JcoupLocal_2_12_we0;
output  [511:0] JcoupLocal_2_12_d0;
input  [511:0] JcoupLocal_2_12_q0;
output  [3:0] JcoupLocal_2_13_address0;
output   JcoupLocal_2_13_ce0;
output   JcoupLocal_2_13_we0;
output  [511:0] JcoupLocal_2_13_d0;
input  [511:0] JcoupLocal_2_13_q0;
output  [3:0] JcoupLocal_2_14_address0;
output   JcoupLocal_2_14_ce0;
output   JcoupLocal_2_14_we0;
output  [511:0] JcoupLocal_2_14_d0;
input  [511:0] JcoupLocal_2_14_q0;
output  [3:0] JcoupLocal_2_15_address0;
output   JcoupLocal_2_15_ce0;
output   JcoupLocal_2_15_we0;
output  [511:0] JcoupLocal_2_15_d0;
input  [511:0] JcoupLocal_2_15_q0;
output  [3:0] JcoupLocal_3_0_address0;
output   JcoupLocal_3_0_ce0;
output   JcoupLocal_3_0_we0;
output  [511:0] JcoupLocal_3_0_d0;
output  [3:0] JcoupLocal_3_1_address0;
output   JcoupLocal_3_1_ce0;
output   JcoupLocal_3_1_we0;
output  [511:0] JcoupLocal_3_1_d0;
output  [3:0] JcoupLocal_3_2_address0;
output   JcoupLocal_3_2_ce0;
output   JcoupLocal_3_2_we0;
output  [511:0] JcoupLocal_3_2_d0;
output  [3:0] JcoupLocal_3_3_address0;
output   JcoupLocal_3_3_ce0;
output   JcoupLocal_3_3_we0;
output  [511:0] JcoupLocal_3_3_d0;
output  [3:0] JcoupLocal_3_4_address0;
output   JcoupLocal_3_4_ce0;
output   JcoupLocal_3_4_we0;
output  [511:0] JcoupLocal_3_4_d0;
output  [3:0] JcoupLocal_3_5_address0;
output   JcoupLocal_3_5_ce0;
output   JcoupLocal_3_5_we0;
output  [511:0] JcoupLocal_3_5_d0;
output  [3:0] JcoupLocal_3_6_address0;
output   JcoupLocal_3_6_ce0;
output   JcoupLocal_3_6_we0;
output  [511:0] JcoupLocal_3_6_d0;
output  [3:0] JcoupLocal_3_7_address0;
output   JcoupLocal_3_7_ce0;
output   JcoupLocal_3_7_we0;
output  [511:0] JcoupLocal_3_7_d0;
output  [3:0] JcoupLocal_3_8_address0;
output   JcoupLocal_3_8_ce0;
output   JcoupLocal_3_8_we0;
output  [511:0] JcoupLocal_3_8_d0;
output  [3:0] JcoupLocal_3_9_address0;
output   JcoupLocal_3_9_ce0;
output   JcoupLocal_3_9_we0;
output  [511:0] JcoupLocal_3_9_d0;
output  [3:0] JcoupLocal_3_10_address0;
output   JcoupLocal_3_10_ce0;
output   JcoupLocal_3_10_we0;
output  [511:0] JcoupLocal_3_10_d0;
output  [3:0] JcoupLocal_3_11_address0;
output   JcoupLocal_3_11_ce0;
output   JcoupLocal_3_11_we0;
output  [511:0] JcoupLocal_3_11_d0;
output  [3:0] JcoupLocal_3_12_address0;
output   JcoupLocal_3_12_ce0;
output   JcoupLocal_3_12_we0;
output  [511:0] JcoupLocal_3_12_d0;
output  [3:0] JcoupLocal_3_13_address0;
output   JcoupLocal_3_13_ce0;
output   JcoupLocal_3_13_we0;
output  [511:0] JcoupLocal_3_13_d0;
output  [3:0] JcoupLocal_3_14_address0;
output   JcoupLocal_3_14_ce0;
output   JcoupLocal_3_14_we0;
output  [511:0] JcoupLocal_3_14_d0;
output  [3:0] JcoupLocal_3_15_address0;
output   JcoupLocal_3_15_ce0;
output   JcoupLocal_3_15_we0;
output  [511:0] JcoupLocal_3_15_d0;

reg ap_idle;
reg JcoupLocal_0_0_ce0;
reg JcoupLocal_0_1_ce0;
reg JcoupLocal_0_2_ce0;
reg JcoupLocal_0_3_ce0;
reg JcoupLocal_0_4_ce0;
reg JcoupLocal_0_5_ce0;
reg JcoupLocal_0_6_ce0;
reg JcoupLocal_0_7_ce0;
reg JcoupLocal_0_8_ce0;
reg JcoupLocal_0_9_ce0;
reg JcoupLocal_0_10_ce0;
reg JcoupLocal_0_11_ce0;
reg JcoupLocal_0_12_ce0;
reg JcoupLocal_0_13_ce0;
reg JcoupLocal_0_14_ce0;
reg JcoupLocal_0_15_ce0;
reg JcoupLocal_1_0_ce0;
reg JcoupLocal_1_0_we0;
reg JcoupLocal_1_1_ce0;
reg JcoupLocal_1_1_we0;
reg JcoupLocal_1_2_ce0;
reg JcoupLocal_1_2_we0;
reg JcoupLocal_1_3_ce0;
reg JcoupLocal_1_3_we0;
reg JcoupLocal_1_4_ce0;
reg JcoupLocal_1_4_we0;
reg JcoupLocal_1_5_ce0;
reg JcoupLocal_1_5_we0;
reg JcoupLocal_1_6_ce0;
reg JcoupLocal_1_6_we0;
reg JcoupLocal_1_7_ce0;
reg JcoupLocal_1_7_we0;
reg JcoupLocal_1_8_ce0;
reg JcoupLocal_1_8_we0;
reg JcoupLocal_1_9_ce0;
reg JcoupLocal_1_9_we0;
reg JcoupLocal_1_10_ce0;
reg JcoupLocal_1_10_we0;
reg JcoupLocal_1_11_ce0;
reg JcoupLocal_1_11_we0;
reg JcoupLocal_1_12_ce0;
reg JcoupLocal_1_12_we0;
reg JcoupLocal_1_13_ce0;
reg JcoupLocal_1_13_we0;
reg JcoupLocal_1_14_ce0;
reg JcoupLocal_1_14_we0;
reg JcoupLocal_1_15_ce0;
reg JcoupLocal_1_15_we0;
reg JcoupLocal_2_0_ce0;
reg JcoupLocal_2_0_we0;
reg JcoupLocal_2_1_ce0;
reg JcoupLocal_2_1_we0;
reg JcoupLocal_2_2_ce0;
reg JcoupLocal_2_2_we0;
reg JcoupLocal_2_3_ce0;
reg JcoupLocal_2_3_we0;
reg JcoupLocal_2_4_ce0;
reg JcoupLocal_2_4_we0;
reg JcoupLocal_2_5_ce0;
reg JcoupLocal_2_5_we0;
reg JcoupLocal_2_6_ce0;
reg JcoupLocal_2_6_we0;
reg JcoupLocal_2_7_ce0;
reg JcoupLocal_2_7_we0;
reg JcoupLocal_2_8_ce0;
reg JcoupLocal_2_8_we0;
reg JcoupLocal_2_9_ce0;
reg JcoupLocal_2_9_we0;
reg JcoupLocal_2_10_ce0;
reg JcoupLocal_2_10_we0;
reg JcoupLocal_2_11_ce0;
reg JcoupLocal_2_11_we0;
reg JcoupLocal_2_12_ce0;
reg JcoupLocal_2_12_we0;
reg JcoupLocal_2_13_ce0;
reg JcoupLocal_2_13_we0;
reg JcoupLocal_2_14_ce0;
reg JcoupLocal_2_14_we0;
reg JcoupLocal_2_15_ce0;
reg JcoupLocal_2_15_we0;
reg JcoupLocal_3_0_ce0;
reg JcoupLocal_3_0_we0;
reg JcoupLocal_3_1_ce0;
reg JcoupLocal_3_1_we0;
reg JcoupLocal_3_2_ce0;
reg JcoupLocal_3_2_we0;
reg JcoupLocal_3_3_ce0;
reg JcoupLocal_3_3_we0;
reg JcoupLocal_3_4_ce0;
reg JcoupLocal_3_4_we0;
reg JcoupLocal_3_5_ce0;
reg JcoupLocal_3_5_we0;
reg JcoupLocal_3_6_ce0;
reg JcoupLocal_3_6_we0;
reg JcoupLocal_3_7_ce0;
reg JcoupLocal_3_7_we0;
reg JcoupLocal_3_8_ce0;
reg JcoupLocal_3_8_we0;
reg JcoupLocal_3_9_ce0;
reg JcoupLocal_3_9_we0;
reg JcoupLocal_3_10_ce0;
reg JcoupLocal_3_10_we0;
reg JcoupLocal_3_11_ce0;
reg JcoupLocal_3_11_we0;
reg JcoupLocal_3_12_ce0;
reg JcoupLocal_3_12_we0;
reg JcoupLocal_3_13_ce0;
reg JcoupLocal_3_13_we0;
reg JcoupLocal_3_14_ce0;
reg JcoupLocal_3_14_we0;
reg JcoupLocal_3_15_ce0;
reg JcoupLocal_3_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln264_fu_1036_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln268_fu_1048_p1;
reg   [3:0] trunc_ln268_reg_1261;
reg   [3:0] trunc_ln268_reg_1261_pp0_iter1_reg;
reg   [3:0] trunc_ln268_reg_1261_pp0_iter2_reg;
wire   [63:0] zext_ln268_1_fu_1062_p1;
reg   [63:0] zext_ln268_1_reg_1266;
reg   [63:0] zext_ln268_1_reg_1266_pp0_iter1_reg;
reg   [63:0] zext_ln268_1_reg_1266_pp0_iter2_reg;
wire   [63:0] zext_ln268_fu_1087_p1;
reg   [63:0] zext_ln268_reg_1398;
reg   [63:0] zext_ln268_reg_1398_pp0_iter2_reg;
wire    ap_block_pp0_stage0;
reg   [8:0] packOfst_fu_192;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_packOfst_1;
wire   [8:0] add_ln264_fu_1042_p2;
wire   [511:0] tmp_fu_1090_p18;
wire   [511:0] tmp_16_fu_1144_p18;
wire   [511:0] tmp_s_fu_1197_p18;
wire   [3:0] lshr_ln268_s_fu_1052_p4;
wire   [63:0] tmp_fu_1090_p17;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

QuantumMonteCarloU50_mux_1664_512_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 512 ),
    .din1_WIDTH( 512 ),
    .din2_WIDTH( 512 ),
    .din3_WIDTH( 512 ),
    .din4_WIDTH( 512 ),
    .din5_WIDTH( 512 ),
    .din6_WIDTH( 512 ),
    .din7_WIDTH( 512 ),
    .din8_WIDTH( 512 ),
    .din9_WIDTH( 512 ),
    .din10_WIDTH( 512 ),
    .din11_WIDTH( 512 ),
    .din12_WIDTH( 512 ),
    .din13_WIDTH( 512 ),
    .din14_WIDTH( 512 ),
    .din15_WIDTH( 512 ),
    .din16_WIDTH( 64 ),
    .dout_WIDTH( 512 ))
mux_1664_512_1_1_U521(
    .din0(JcoupLocal_0_0_q0),
    .din1(JcoupLocal_0_1_q0),
    .din2(JcoupLocal_0_2_q0),
    .din3(JcoupLocal_0_3_q0),
    .din4(JcoupLocal_0_4_q0),
    .din5(JcoupLocal_0_5_q0),
    .din6(JcoupLocal_0_6_q0),
    .din7(JcoupLocal_0_7_q0),
    .din8(JcoupLocal_0_8_q0),
    .din9(JcoupLocal_0_9_q0),
    .din10(JcoupLocal_0_10_q0),
    .din11(JcoupLocal_0_11_q0),
    .din12(JcoupLocal_0_12_q0),
    .din13(JcoupLocal_0_13_q0),
    .din14(JcoupLocal_0_14_q0),
    .din15(JcoupLocal_0_15_q0),
    .din16(tmp_fu_1090_p17),
    .dout(tmp_fu_1090_p18)
);

QuantumMonteCarloU50_mux_1664_512_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 512 ),
    .din1_WIDTH( 512 ),
    .din2_WIDTH( 512 ),
    .din3_WIDTH( 512 ),
    .din4_WIDTH( 512 ),
    .din5_WIDTH( 512 ),
    .din6_WIDTH( 512 ),
    .din7_WIDTH( 512 ),
    .din8_WIDTH( 512 ),
    .din9_WIDTH( 512 ),
    .din10_WIDTH( 512 ),
    .din11_WIDTH( 512 ),
    .din12_WIDTH( 512 ),
    .din13_WIDTH( 512 ),
    .din14_WIDTH( 512 ),
    .din15_WIDTH( 512 ),
    .din16_WIDTH( 64 ),
    .dout_WIDTH( 512 ))
mux_1664_512_1_1_U522(
    .din0(JcoupLocal_1_0_q0),
    .din1(JcoupLocal_1_1_q0),
    .din2(JcoupLocal_1_2_q0),
    .din3(JcoupLocal_1_3_q0),
    .din4(JcoupLocal_1_4_q0),
    .din5(JcoupLocal_1_5_q0),
    .din6(JcoupLocal_1_6_q0),
    .din7(JcoupLocal_1_7_q0),
    .din8(JcoupLocal_1_8_q0),
    .din9(JcoupLocal_1_9_q0),
    .din10(JcoupLocal_1_10_q0),
    .din11(JcoupLocal_1_11_q0),
    .din12(JcoupLocal_1_12_q0),
    .din13(JcoupLocal_1_13_q0),
    .din14(JcoupLocal_1_14_q0),
    .din15(JcoupLocal_1_15_q0),
    .din16(zext_ln268_reg_1398),
    .dout(tmp_16_fu_1144_p18)
);

QuantumMonteCarloU50_mux_1664_512_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 512 ),
    .din1_WIDTH( 512 ),
    .din2_WIDTH( 512 ),
    .din3_WIDTH( 512 ),
    .din4_WIDTH( 512 ),
    .din5_WIDTH( 512 ),
    .din6_WIDTH( 512 ),
    .din7_WIDTH( 512 ),
    .din8_WIDTH( 512 ),
    .din9_WIDTH( 512 ),
    .din10_WIDTH( 512 ),
    .din11_WIDTH( 512 ),
    .din12_WIDTH( 512 ),
    .din13_WIDTH( 512 ),
    .din14_WIDTH( 512 ),
    .din15_WIDTH( 512 ),
    .din16_WIDTH( 64 ),
    .dout_WIDTH( 512 ))
mux_1664_512_1_1_U523(
    .din0(JcoupLocal_2_0_q0),
    .din1(JcoupLocal_2_1_q0),
    .din2(JcoupLocal_2_2_q0),
    .din3(JcoupLocal_2_3_q0),
    .din4(JcoupLocal_2_4_q0),
    .din5(JcoupLocal_2_5_q0),
    .din6(JcoupLocal_2_6_q0),
    .din7(JcoupLocal_2_7_q0),
    .din8(JcoupLocal_2_8_q0),
    .din9(JcoupLocal_2_9_q0),
    .din10(JcoupLocal_2_10_q0),
    .din11(JcoupLocal_2_11_q0),
    .din12(JcoupLocal_2_12_q0),
    .din13(JcoupLocal_2_13_q0),
    .din14(JcoupLocal_2_14_q0),
    .din15(JcoupLocal_2_15_q0),
    .din16(zext_ln268_reg_1398_pp0_iter2_reg),
    .dout(tmp_s_fu_1197_p18)
);

QuantumMonteCarloU50_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln264_fu_1036_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            packOfst_fu_192 <= add_ln264_fu_1042_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            packOfst_fu_192 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln268_reg_1261_pp0_iter1_reg <= trunc_ln268_reg_1261;
        zext_ln268_1_reg_1266_pp0_iter1_reg[3 : 0] <= zext_ln268_1_reg_1266[3 : 0];
        zext_ln268_reg_1398[3 : 0] <= zext_ln268_fu_1087_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln264_fu_1036_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln268_reg_1261 <= trunc_ln268_fu_1048_p1;
        zext_ln268_1_reg_1266[3 : 0] <= zext_ln268_1_fu_1062_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        trunc_ln268_reg_1261_pp0_iter2_reg <= trunc_ln268_reg_1261_pp0_iter1_reg;
        zext_ln268_1_reg_1266_pp0_iter2_reg[3 : 0] <= zext_ln268_1_reg_1266_pp0_iter1_reg[3 : 0];
        zext_ln268_reg_1398_pp0_iter2_reg[3 : 0] <= zext_ln268_reg_1398[3 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_0_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_10_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_11_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_12_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_13_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_14_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_15_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_1_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_2_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_3_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_4_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_5_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_6_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_7_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_8_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_0_9_ce0 = 1'b1;
    end else begin
        JcoupLocal_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_0_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_0_we0 = 1'b1;
    end else begin
        JcoupLocal_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_10_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_10_we0 = 1'b1;
    end else begin
        JcoupLocal_1_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_11_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_11_we0 = 1'b1;
    end else begin
        JcoupLocal_1_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_12_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_12_we0 = 1'b1;
    end else begin
        JcoupLocal_1_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_13_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_13_we0 = 1'b1;
    end else begin
        JcoupLocal_1_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_14_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_14_we0 = 1'b1;
    end else begin
        JcoupLocal_1_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_15_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_15_we0 = 1'b1;
    end else begin
        JcoupLocal_1_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_1_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_1_we0 = 1'b1;
    end else begin
        JcoupLocal_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_2_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_2_we0 = 1'b1;
    end else begin
        JcoupLocal_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_3_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_3_we0 = 1'b1;
    end else begin
        JcoupLocal_1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_4_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_4_we0 = 1'b1;
    end else begin
        JcoupLocal_1_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_5_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_5_we0 = 1'b1;
    end else begin
        JcoupLocal_1_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_6_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_6_we0 = 1'b1;
    end else begin
        JcoupLocal_1_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_7_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_7_we0 = 1'b1;
    end else begin
        JcoupLocal_1_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_8_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_8_we0 = 1'b1;
    end else begin
        JcoupLocal_1_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_9_ce0 = 1'b1;
    end else begin
        JcoupLocal_1_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        JcoupLocal_1_9_we0 = 1'b1;
    end else begin
        JcoupLocal_1_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_0_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_0_we0 = 1'b1;
    end else begin
        JcoupLocal_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_10_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_10_we0 = 1'b1;
    end else begin
        JcoupLocal_2_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_11_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_11_we0 = 1'b1;
    end else begin
        JcoupLocal_2_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_12_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_12_we0 = 1'b1;
    end else begin
        JcoupLocal_2_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_13_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_13_we0 = 1'b1;
    end else begin
        JcoupLocal_2_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_14_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_14_we0 = 1'b1;
    end else begin
        JcoupLocal_2_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_15_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_15_we0 = 1'b1;
    end else begin
        JcoupLocal_2_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_1_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_1_we0 = 1'b1;
    end else begin
        JcoupLocal_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_2_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_2_we0 = 1'b1;
    end else begin
        JcoupLocal_2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_3_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_3_we0 = 1'b1;
    end else begin
        JcoupLocal_2_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_4_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_4_we0 = 1'b1;
    end else begin
        JcoupLocal_2_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_5_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_5_we0 = 1'b1;
    end else begin
        JcoupLocal_2_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_6_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_6_we0 = 1'b1;
    end else begin
        JcoupLocal_2_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_7_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_7_we0 = 1'b1;
    end else begin
        JcoupLocal_2_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_8_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_8_we0 = 1'b1;
    end else begin
        JcoupLocal_2_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_9_ce0 = 1'b1;
    end else begin
        JcoupLocal_2_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter1_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        JcoupLocal_2_9_we0 = 1'b1;
    end else begin
        JcoupLocal_2_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_0_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_0_we0 = 1'b1;
    end else begin
        JcoupLocal_3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_10_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_10_we0 = 1'b1;
    end else begin
        JcoupLocal_3_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_11_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_11_we0 = 1'b1;
    end else begin
        JcoupLocal_3_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_12_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_12_we0 = 1'b1;
    end else begin
        JcoupLocal_3_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_13_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_13_we0 = 1'b1;
    end else begin
        JcoupLocal_3_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_14_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_14_we0 = 1'b1;
    end else begin
        JcoupLocal_3_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_15_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_15_we0 = 1'b1;
    end else begin
        JcoupLocal_3_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_1_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_1_we0 = 1'b1;
    end else begin
        JcoupLocal_3_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_2_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_2_we0 = 1'b1;
    end else begin
        JcoupLocal_3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_3_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_3_we0 = 1'b1;
    end else begin
        JcoupLocal_3_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_4_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_4_we0 = 1'b1;
    end else begin
        JcoupLocal_3_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_5_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_5_we0 = 1'b1;
    end else begin
        JcoupLocal_3_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_6_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_6_we0 = 1'b1;
    end else begin
        JcoupLocal_3_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_7_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_7_we0 = 1'b1;
    end else begin
        JcoupLocal_3_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_8_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_8_we0 = 1'b1;
    end else begin
        JcoupLocal_3_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_9_ce0 = 1'b1;
    end else begin
        JcoupLocal_3_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln268_reg_1261_pp0_iter2_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        JcoupLocal_3_9_we0 = 1'b1;
    end else begin
        JcoupLocal_3_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln264_fu_1036_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_packOfst_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_packOfst_1 = packOfst_fu_192;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign JcoupLocal_0_0_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_10_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_11_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_12_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_13_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_14_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_15_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_1_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_2_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_3_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_4_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_5_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_6_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_7_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_8_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_0_9_address0 = zext_ln268_1_fu_1062_p1;

assign JcoupLocal_1_0_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_0_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_10_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_10_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_11_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_11_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_12_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_12_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_13_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_13_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_14_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_14_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_15_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_15_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_1_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_1_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_2_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_2_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_3_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_3_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_4_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_4_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_5_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_5_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_6_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_6_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_7_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_7_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_8_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_8_d0 = tmp_fu_1090_p18;

assign JcoupLocal_1_9_address0 = zext_ln268_1_reg_1266;

assign JcoupLocal_1_9_d0 = tmp_fu_1090_p18;

assign JcoupLocal_2_0_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_0_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_10_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_10_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_11_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_11_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_12_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_12_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_13_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_13_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_14_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_14_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_15_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_15_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_1_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_1_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_2_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_2_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_3_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_3_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_4_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_4_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_5_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_5_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_6_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_6_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_7_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_7_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_8_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_8_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_2_9_address0 = zext_ln268_1_reg_1266_pp0_iter1_reg;

assign JcoupLocal_2_9_d0 = tmp_16_fu_1144_p18;

assign JcoupLocal_3_0_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_0_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_10_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_10_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_11_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_11_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_12_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_12_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_13_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_13_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_14_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_14_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_15_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_15_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_1_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_1_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_2_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_2_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_3_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_3_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_4_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_4_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_5_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_5_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_6_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_6_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_7_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_7_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_8_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_8_d0 = tmp_s_fu_1197_p18;

assign JcoupLocal_3_9_address0 = zext_ln268_1_reg_1266_pp0_iter2_reg;

assign JcoupLocal_3_9_d0 = tmp_s_fu_1197_p18;

assign add_ln264_fu_1042_p2 = (ap_sig_allocacmp_packOfst_1 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln264_fu_1036_p2 = ((ap_sig_allocacmp_packOfst_1 == 9'd256) ? 1'b1 : 1'b0);

assign lshr_ln268_s_fu_1052_p4 = {{ap_sig_allocacmp_packOfst_1[7:4]}};

assign tmp_fu_1090_p17 = trunc_ln268_reg_1261;

assign trunc_ln268_fu_1048_p1 = ap_sig_allocacmp_packOfst_1[3:0];

assign zext_ln268_1_fu_1062_p1 = lshr_ln268_s_fu_1052_p4;

assign zext_ln268_fu_1087_p1 = trunc_ln268_reg_1261;

always @ (posedge ap_clk) begin
    zext_ln268_1_reg_1266[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln268_1_reg_1266_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln268_1_reg_1266_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln268_reg_1398[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln268_reg_1398_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //QuantumMonteCarloU50_QuantumMonteCarloU50_Pipeline_SHIFT_JCOUP
