// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module QuantumMonteCarloU50_QuantumMonteCarloU50_Pipeline_WRITE_TROTTERS_VITIS_LOOP_303_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        sext_ln187,
        trottersLocal_V_0_0_address0,
        trottersLocal_V_0_0_ce0,
        trottersLocal_V_0_0_q0,
        trottersLocal_V_0_1_address0,
        trottersLocal_V_0_1_ce0,
        trottersLocal_V_0_1_q0,
        trottersLocal_V_0_2_address0,
        trottersLocal_V_0_2_ce0,
        trottersLocal_V_0_2_q0,
        trottersLocal_V_0_3_address0,
        trottersLocal_V_0_3_ce0,
        trottersLocal_V_0_3_q0,
        trottersLocal_V_0_4_address0,
        trottersLocal_V_0_4_ce0,
        trottersLocal_V_0_4_q0,
        trottersLocal_V_0_5_address0,
        trottersLocal_V_0_5_ce0,
        trottersLocal_V_0_5_q0,
        trottersLocal_V_0_6_address0,
        trottersLocal_V_0_6_ce0,
        trottersLocal_V_0_6_q0,
        trottersLocal_V_0_7_address0,
        trottersLocal_V_0_7_ce0,
        trottersLocal_V_0_7_q0,
        trottersLocal_V_0_8_address0,
        trottersLocal_V_0_8_ce0,
        trottersLocal_V_0_8_q0,
        trottersLocal_V_0_9_address0,
        trottersLocal_V_0_9_ce0,
        trottersLocal_V_0_9_q0,
        trottersLocal_V_0_10_address0,
        trottersLocal_V_0_10_ce0,
        trottersLocal_V_0_10_q0,
        trottersLocal_V_0_11_address0,
        trottersLocal_V_0_11_ce0,
        trottersLocal_V_0_11_q0,
        trottersLocal_V_0_12_address0,
        trottersLocal_V_0_12_ce0,
        trottersLocal_V_0_12_q0,
        trottersLocal_V_0_13_address0,
        trottersLocal_V_0_13_ce0,
        trottersLocal_V_0_13_q0,
        trottersLocal_V_0_14_address0,
        trottersLocal_V_0_14_ce0,
        trottersLocal_V_0_14_q0,
        trottersLocal_V_0_15_address0,
        trottersLocal_V_0_15_ce0,
        trottersLocal_V_0_15_q0,
        trottersLocal_V_1_0_address0,
        trottersLocal_V_1_0_ce0,
        trottersLocal_V_1_0_q0,
        trottersLocal_V_1_1_address0,
        trottersLocal_V_1_1_ce0,
        trottersLocal_V_1_1_q0,
        trottersLocal_V_1_2_address0,
        trottersLocal_V_1_2_ce0,
        trottersLocal_V_1_2_q0,
        trottersLocal_V_1_3_address0,
        trottersLocal_V_1_3_ce0,
        trottersLocal_V_1_3_q0,
        trottersLocal_V_1_4_address0,
        trottersLocal_V_1_4_ce0,
        trottersLocal_V_1_4_q0,
        trottersLocal_V_1_5_address0,
        trottersLocal_V_1_5_ce0,
        trottersLocal_V_1_5_q0,
        trottersLocal_V_1_6_address0,
        trottersLocal_V_1_6_ce0,
        trottersLocal_V_1_6_q0,
        trottersLocal_V_1_7_address0,
        trottersLocal_V_1_7_ce0,
        trottersLocal_V_1_7_q0,
        trottersLocal_V_1_8_address0,
        trottersLocal_V_1_8_ce0,
        trottersLocal_V_1_8_q0,
        trottersLocal_V_1_9_address0,
        trottersLocal_V_1_9_ce0,
        trottersLocal_V_1_9_q0,
        trottersLocal_V_1_10_address0,
        trottersLocal_V_1_10_ce0,
        trottersLocal_V_1_10_q0,
        trottersLocal_V_1_11_address0,
        trottersLocal_V_1_11_ce0,
        trottersLocal_V_1_11_q0,
        trottersLocal_V_1_12_address0,
        trottersLocal_V_1_12_ce0,
        trottersLocal_V_1_12_q0,
        trottersLocal_V_1_13_address0,
        trottersLocal_V_1_13_ce0,
        trottersLocal_V_1_13_q0,
        trottersLocal_V_1_14_address0,
        trottersLocal_V_1_14_ce0,
        trottersLocal_V_1_14_q0,
        trottersLocal_V_1_15_address0,
        trottersLocal_V_1_15_ce0,
        trottersLocal_V_1_15_q0,
        trottersLocal_V_2_0_address0,
        trottersLocal_V_2_0_ce0,
        trottersLocal_V_2_0_q0,
        trottersLocal_V_2_1_address0,
        trottersLocal_V_2_1_ce0,
        trottersLocal_V_2_1_q0,
        trottersLocal_V_2_2_address0,
        trottersLocal_V_2_2_ce0,
        trottersLocal_V_2_2_q0,
        trottersLocal_V_2_3_address0,
        trottersLocal_V_2_3_ce0,
        trottersLocal_V_2_3_q0,
        trottersLocal_V_2_4_address0,
        trottersLocal_V_2_4_ce0,
        trottersLocal_V_2_4_q0,
        trottersLocal_V_2_5_address0,
        trottersLocal_V_2_5_ce0,
        trottersLocal_V_2_5_q0,
        trottersLocal_V_2_6_address0,
        trottersLocal_V_2_6_ce0,
        trottersLocal_V_2_6_q0,
        trottersLocal_V_2_7_address0,
        trottersLocal_V_2_7_ce0,
        trottersLocal_V_2_7_q0,
        trottersLocal_V_2_8_address0,
        trottersLocal_V_2_8_ce0,
        trottersLocal_V_2_8_q0,
        trottersLocal_V_2_9_address0,
        trottersLocal_V_2_9_ce0,
        trottersLocal_V_2_9_q0,
        trottersLocal_V_2_10_address0,
        trottersLocal_V_2_10_ce0,
        trottersLocal_V_2_10_q0,
        trottersLocal_V_2_11_address0,
        trottersLocal_V_2_11_ce0,
        trottersLocal_V_2_11_q0,
        trottersLocal_V_2_12_address0,
        trottersLocal_V_2_12_ce0,
        trottersLocal_V_2_12_q0,
        trottersLocal_V_2_13_address0,
        trottersLocal_V_2_13_ce0,
        trottersLocal_V_2_13_q0,
        trottersLocal_V_2_14_address0,
        trottersLocal_V_2_14_ce0,
        trottersLocal_V_2_14_q0,
        trottersLocal_V_2_15_address0,
        trottersLocal_V_2_15_ce0,
        trottersLocal_V_2_15_q0,
        trottersLocal_V_3_0_address0,
        trottersLocal_V_3_0_ce0,
        trottersLocal_V_3_0_q0,
        trottersLocal_V_3_1_address0,
        trottersLocal_V_3_1_ce0,
        trottersLocal_V_3_1_q0,
        trottersLocal_V_3_2_address0,
        trottersLocal_V_3_2_ce0,
        trottersLocal_V_3_2_q0,
        trottersLocal_V_3_3_address0,
        trottersLocal_V_3_3_ce0,
        trottersLocal_V_3_3_q0,
        trottersLocal_V_3_4_address0,
        trottersLocal_V_3_4_ce0,
        trottersLocal_V_3_4_q0,
        trottersLocal_V_3_5_address0,
        trottersLocal_V_3_5_ce0,
        trottersLocal_V_3_5_q0,
        trottersLocal_V_3_6_address0,
        trottersLocal_V_3_6_ce0,
        trottersLocal_V_3_6_q0,
        trottersLocal_V_3_7_address0,
        trottersLocal_V_3_7_ce0,
        trottersLocal_V_3_7_q0,
        trottersLocal_V_3_8_address0,
        trottersLocal_V_3_8_ce0,
        trottersLocal_V_3_8_q0,
        trottersLocal_V_3_9_address0,
        trottersLocal_V_3_9_ce0,
        trottersLocal_V_3_9_q0,
        trottersLocal_V_3_10_address0,
        trottersLocal_V_3_10_ce0,
        trottersLocal_V_3_10_q0,
        trottersLocal_V_3_11_address0,
        trottersLocal_V_3_11_ce0,
        trottersLocal_V_3_11_q0,
        trottersLocal_V_3_12_address0,
        trottersLocal_V_3_12_ce0,
        trottersLocal_V_3_12_q0,
        trottersLocal_V_3_13_address0,
        trottersLocal_V_3_13_ce0,
        trottersLocal_V_3_13_q0,
        trottersLocal_V_3_14_address0,
        trottersLocal_V_3_14_ce0,
        trottersLocal_V_3_14_q0,
        trottersLocal_V_3_15_address0,
        trottersLocal_V_3_15_ce0,
        trottersLocal_V_3_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [511:0] m_axi_gmem_WDATA;
output  [63:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [511:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [57:0] sext_ln187;
output  [3:0] trottersLocal_V_0_0_address0;
output   trottersLocal_V_0_0_ce0;
input  [15:0] trottersLocal_V_0_0_q0;
output  [3:0] trottersLocal_V_0_1_address0;
output   trottersLocal_V_0_1_ce0;
input  [15:0] trottersLocal_V_0_1_q0;
output  [3:0] trottersLocal_V_0_2_address0;
output   trottersLocal_V_0_2_ce0;
input  [15:0] trottersLocal_V_0_2_q0;
output  [3:0] trottersLocal_V_0_3_address0;
output   trottersLocal_V_0_3_ce0;
input  [15:0] trottersLocal_V_0_3_q0;
output  [3:0] trottersLocal_V_0_4_address0;
output   trottersLocal_V_0_4_ce0;
input  [15:0] trottersLocal_V_0_4_q0;
output  [3:0] trottersLocal_V_0_5_address0;
output   trottersLocal_V_0_5_ce0;
input  [15:0] trottersLocal_V_0_5_q0;
output  [3:0] trottersLocal_V_0_6_address0;
output   trottersLocal_V_0_6_ce0;
input  [15:0] trottersLocal_V_0_6_q0;
output  [3:0] trottersLocal_V_0_7_address0;
output   trottersLocal_V_0_7_ce0;
input  [15:0] trottersLocal_V_0_7_q0;
output  [3:0] trottersLocal_V_0_8_address0;
output   trottersLocal_V_0_8_ce0;
input  [15:0] trottersLocal_V_0_8_q0;
output  [3:0] trottersLocal_V_0_9_address0;
output   trottersLocal_V_0_9_ce0;
input  [15:0] trottersLocal_V_0_9_q0;
output  [3:0] trottersLocal_V_0_10_address0;
output   trottersLocal_V_0_10_ce0;
input  [15:0] trottersLocal_V_0_10_q0;
output  [3:0] trottersLocal_V_0_11_address0;
output   trottersLocal_V_0_11_ce0;
input  [15:0] trottersLocal_V_0_11_q0;
output  [3:0] trottersLocal_V_0_12_address0;
output   trottersLocal_V_0_12_ce0;
input  [15:0] trottersLocal_V_0_12_q0;
output  [3:0] trottersLocal_V_0_13_address0;
output   trottersLocal_V_0_13_ce0;
input  [15:0] trottersLocal_V_0_13_q0;
output  [3:0] trottersLocal_V_0_14_address0;
output   trottersLocal_V_0_14_ce0;
input  [15:0] trottersLocal_V_0_14_q0;
output  [3:0] trottersLocal_V_0_15_address0;
output   trottersLocal_V_0_15_ce0;
input  [15:0] trottersLocal_V_0_15_q0;
output  [3:0] trottersLocal_V_1_0_address0;
output   trottersLocal_V_1_0_ce0;
input  [15:0] trottersLocal_V_1_0_q0;
output  [3:0] trottersLocal_V_1_1_address0;
output   trottersLocal_V_1_1_ce0;
input  [15:0] trottersLocal_V_1_1_q0;
output  [3:0] trottersLocal_V_1_2_address0;
output   trottersLocal_V_1_2_ce0;
input  [15:0] trottersLocal_V_1_2_q0;
output  [3:0] trottersLocal_V_1_3_address0;
output   trottersLocal_V_1_3_ce0;
input  [15:0] trottersLocal_V_1_3_q0;
output  [3:0] trottersLocal_V_1_4_address0;
output   trottersLocal_V_1_4_ce0;
input  [15:0] trottersLocal_V_1_4_q0;
output  [3:0] trottersLocal_V_1_5_address0;
output   trottersLocal_V_1_5_ce0;
input  [15:0] trottersLocal_V_1_5_q0;
output  [3:0] trottersLocal_V_1_6_address0;
output   trottersLocal_V_1_6_ce0;
input  [15:0] trottersLocal_V_1_6_q0;
output  [3:0] trottersLocal_V_1_7_address0;
output   trottersLocal_V_1_7_ce0;
input  [15:0] trottersLocal_V_1_7_q0;
output  [3:0] trottersLocal_V_1_8_address0;
output   trottersLocal_V_1_8_ce0;
input  [15:0] trottersLocal_V_1_8_q0;
output  [3:0] trottersLocal_V_1_9_address0;
output   trottersLocal_V_1_9_ce0;
input  [15:0] trottersLocal_V_1_9_q0;
output  [3:0] trottersLocal_V_1_10_address0;
output   trottersLocal_V_1_10_ce0;
input  [15:0] trottersLocal_V_1_10_q0;
output  [3:0] trottersLocal_V_1_11_address0;
output   trottersLocal_V_1_11_ce0;
input  [15:0] trottersLocal_V_1_11_q0;
output  [3:0] trottersLocal_V_1_12_address0;
output   trottersLocal_V_1_12_ce0;
input  [15:0] trottersLocal_V_1_12_q0;
output  [3:0] trottersLocal_V_1_13_address0;
output   trottersLocal_V_1_13_ce0;
input  [15:0] trottersLocal_V_1_13_q0;
output  [3:0] trottersLocal_V_1_14_address0;
output   trottersLocal_V_1_14_ce0;
input  [15:0] trottersLocal_V_1_14_q0;
output  [3:0] trottersLocal_V_1_15_address0;
output   trottersLocal_V_1_15_ce0;
input  [15:0] trottersLocal_V_1_15_q0;
output  [3:0] trottersLocal_V_2_0_address0;
output   trottersLocal_V_2_0_ce0;
input  [15:0] trottersLocal_V_2_0_q0;
output  [3:0] trottersLocal_V_2_1_address0;
output   trottersLocal_V_2_1_ce0;
input  [15:0] trottersLocal_V_2_1_q0;
output  [3:0] trottersLocal_V_2_2_address0;
output   trottersLocal_V_2_2_ce0;
input  [15:0] trottersLocal_V_2_2_q0;
output  [3:0] trottersLocal_V_2_3_address0;
output   trottersLocal_V_2_3_ce0;
input  [15:0] trottersLocal_V_2_3_q0;
output  [3:0] trottersLocal_V_2_4_address0;
output   trottersLocal_V_2_4_ce0;
input  [15:0] trottersLocal_V_2_4_q0;
output  [3:0] trottersLocal_V_2_5_address0;
output   trottersLocal_V_2_5_ce0;
input  [15:0] trottersLocal_V_2_5_q0;
output  [3:0] trottersLocal_V_2_6_address0;
output   trottersLocal_V_2_6_ce0;
input  [15:0] trottersLocal_V_2_6_q0;
output  [3:0] trottersLocal_V_2_7_address0;
output   trottersLocal_V_2_7_ce0;
input  [15:0] trottersLocal_V_2_7_q0;
output  [3:0] trottersLocal_V_2_8_address0;
output   trottersLocal_V_2_8_ce0;
input  [15:0] trottersLocal_V_2_8_q0;
output  [3:0] trottersLocal_V_2_9_address0;
output   trottersLocal_V_2_9_ce0;
input  [15:0] trottersLocal_V_2_9_q0;
output  [3:0] trottersLocal_V_2_10_address0;
output   trottersLocal_V_2_10_ce0;
input  [15:0] trottersLocal_V_2_10_q0;
output  [3:0] trottersLocal_V_2_11_address0;
output   trottersLocal_V_2_11_ce0;
input  [15:0] trottersLocal_V_2_11_q0;
output  [3:0] trottersLocal_V_2_12_address0;
output   trottersLocal_V_2_12_ce0;
input  [15:0] trottersLocal_V_2_12_q0;
output  [3:0] trottersLocal_V_2_13_address0;
output   trottersLocal_V_2_13_ce0;
input  [15:0] trottersLocal_V_2_13_q0;
output  [3:0] trottersLocal_V_2_14_address0;
output   trottersLocal_V_2_14_ce0;
input  [15:0] trottersLocal_V_2_14_q0;
output  [3:0] trottersLocal_V_2_15_address0;
output   trottersLocal_V_2_15_ce0;
input  [15:0] trottersLocal_V_2_15_q0;
output  [3:0] trottersLocal_V_3_0_address0;
output   trottersLocal_V_3_0_ce0;
input  [15:0] trottersLocal_V_3_0_q0;
output  [3:0] trottersLocal_V_3_1_address0;
output   trottersLocal_V_3_1_ce0;
input  [15:0] trottersLocal_V_3_1_q0;
output  [3:0] trottersLocal_V_3_2_address0;
output   trottersLocal_V_3_2_ce0;
input  [15:0] trottersLocal_V_3_2_q0;
output  [3:0] trottersLocal_V_3_3_address0;
output   trottersLocal_V_3_3_ce0;
input  [15:0] trottersLocal_V_3_3_q0;
output  [3:0] trottersLocal_V_3_4_address0;
output   trottersLocal_V_3_4_ce0;
input  [15:0] trottersLocal_V_3_4_q0;
output  [3:0] trottersLocal_V_3_5_address0;
output   trottersLocal_V_3_5_ce0;
input  [15:0] trottersLocal_V_3_5_q0;
output  [3:0] trottersLocal_V_3_6_address0;
output   trottersLocal_V_3_6_ce0;
input  [15:0] trottersLocal_V_3_6_q0;
output  [3:0] trottersLocal_V_3_7_address0;
output   trottersLocal_V_3_7_ce0;
input  [15:0] trottersLocal_V_3_7_q0;
output  [3:0] trottersLocal_V_3_8_address0;
output   trottersLocal_V_3_8_ce0;
input  [15:0] trottersLocal_V_3_8_q0;
output  [3:0] trottersLocal_V_3_9_address0;
output   trottersLocal_V_3_9_ce0;
input  [15:0] trottersLocal_V_3_9_q0;
output  [3:0] trottersLocal_V_3_10_address0;
output   trottersLocal_V_3_10_ce0;
input  [15:0] trottersLocal_V_3_10_q0;
output  [3:0] trottersLocal_V_3_11_address0;
output   trottersLocal_V_3_11_ce0;
input  [15:0] trottersLocal_V_3_11_q0;
output  [3:0] trottersLocal_V_3_12_address0;
output   trottersLocal_V_3_12_ce0;
input  [15:0] trottersLocal_V_3_12_q0;
output  [3:0] trottersLocal_V_3_13_address0;
output   trottersLocal_V_3_13_ce0;
input  [15:0] trottersLocal_V_3_13_q0;
output  [3:0] trottersLocal_V_3_14_address0;
output   trottersLocal_V_3_14_ce0;
input  [15:0] trottersLocal_V_3_14_q0;
output  [3:0] trottersLocal_V_3_15_address0;
output   trottersLocal_V_3_15_ce0;
input  [15:0] trottersLocal_V_3_15_q0;

reg ap_idle;
reg m_axi_gmem_WVALID;
reg trottersLocal_V_0_0_ce0;
reg trottersLocal_V_0_1_ce0;
reg trottersLocal_V_0_2_ce0;
reg trottersLocal_V_0_3_ce0;
reg trottersLocal_V_0_4_ce0;
reg trottersLocal_V_0_5_ce0;
reg trottersLocal_V_0_6_ce0;
reg trottersLocal_V_0_7_ce0;
reg trottersLocal_V_0_8_ce0;
reg trottersLocal_V_0_9_ce0;
reg trottersLocal_V_0_10_ce0;
reg trottersLocal_V_0_11_ce0;
reg trottersLocal_V_0_12_ce0;
reg trottersLocal_V_0_13_ce0;
reg trottersLocal_V_0_14_ce0;
reg trottersLocal_V_0_15_ce0;
reg trottersLocal_V_1_0_ce0;
reg trottersLocal_V_1_1_ce0;
reg trottersLocal_V_1_2_ce0;
reg trottersLocal_V_1_3_ce0;
reg trottersLocal_V_1_4_ce0;
reg trottersLocal_V_1_5_ce0;
reg trottersLocal_V_1_6_ce0;
reg trottersLocal_V_1_7_ce0;
reg trottersLocal_V_1_8_ce0;
reg trottersLocal_V_1_9_ce0;
reg trottersLocal_V_1_10_ce0;
reg trottersLocal_V_1_11_ce0;
reg trottersLocal_V_1_12_ce0;
reg trottersLocal_V_1_13_ce0;
reg trottersLocal_V_1_14_ce0;
reg trottersLocal_V_1_15_ce0;
reg trottersLocal_V_2_0_ce0;
reg trottersLocal_V_2_1_ce0;
reg trottersLocal_V_2_2_ce0;
reg trottersLocal_V_2_3_ce0;
reg trottersLocal_V_2_4_ce0;
reg trottersLocal_V_2_5_ce0;
reg trottersLocal_V_2_6_ce0;
reg trottersLocal_V_2_7_ce0;
reg trottersLocal_V_2_8_ce0;
reg trottersLocal_V_2_9_ce0;
reg trottersLocal_V_2_10_ce0;
reg trottersLocal_V_2_11_ce0;
reg trottersLocal_V_2_12_ce0;
reg trottersLocal_V_2_13_ce0;
reg trottersLocal_V_2_14_ce0;
reg trottersLocal_V_2_15_ce0;
reg trottersLocal_V_3_0_ce0;
reg trottersLocal_V_3_1_ce0;
reg trottersLocal_V_3_2_ce0;
reg trottersLocal_V_3_3_ce0;
reg trottersLocal_V_3_4_ce0;
reg trottersLocal_V_3_5_ce0;
reg trottersLocal_V_3_6_ce0;
reg trottersLocal_V_3_7_ce0;
reg trottersLocal_V_3_8_ce0;
reg trottersLocal_V_3_9_ce0;
reg trottersLocal_V_3_10_ce0;
reg trottersLocal_V_3_11_ce0;
reg trottersLocal_V_3_12_ce0;
reg trottersLocal_V_3_13_ce0;
reg trottersLocal_V_3_14_ce0;
reg trottersLocal_V_3_15_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] icmp_ln305_reg_1831;
reg   [0:0] icmp_ln305_reg_1831_pp0_iter1_reg;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln302_fu_1099_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln302_reg_1492;
wire   [0:0] icmp_ln303_fu_1117_p2;
reg   [0:0] icmp_ln303_reg_1496;
wire   [1:0] trunc_ln302_fu_1145_p1;
reg   [1:0] trunc_ln302_reg_1501;
wire   [3:0] trunc_ln305_fu_1153_p1;
reg   [3:0] trunc_ln305_reg_1506;
wire   [0:0] icmp_ln305_fu_1235_p2;
wire   [511:0] or_ln_fu_1421_p3;
reg   [511:0] or_ln_reg_1841;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln305_fu_1167_p1;
wire    ap_block_pp0_stage0_01001;
reg   [495:0] phi_ln305_fu_210;
wire   [495:0] select_ln305_fu_1447_p3;
wire    ap_loop_init;
reg   [8:0] packOfst_fu_214;
reg   [8:0] ap_sig_allocacmp_packOfst_load;
wire   [8:0] add_ln303_fu_1241_p2;
reg   [2:0] t_fu_218;
reg   [2:0] ap_sig_allocacmp_t_load;
wire   [2:0] select_ln302_2_fu_1137_p3;
reg   [10:0] indvar_flatten7_fu_222;
reg   [10:0] ap_sig_allocacmp_indvar_flatten7_load;
wire   [10:0] add_ln302_fu_1105_p2;
wire   [2:0] add_ln302_1_fu_1131_p2;
wire   [8:0] select_ln302_fu_1123_p3;
wire   [3:0] lshr_ln_fu_1157_p4;
wire   [4:0] trunc_ln303_fu_1149_p1;
wire   [5:0] tmp_2_fu_1277_p3;
wire   [6:0] tmp_3_fu_1287_p65;
wire   [15:0] tmp_3_fu_1287_p66;
wire   [495:0] select_ln302_1_fu_1270_p3;
wire   [479:0] tmp_1_fu_1429_p4;
wire   [495:0] tmp_6_fu_1439_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

QuantumMonteCarloU50_mux_647_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 16 ),
    .din51_WIDTH( 16 ),
    .din52_WIDTH( 16 ),
    .din53_WIDTH( 16 ),
    .din54_WIDTH( 16 ),
    .din55_WIDTH( 16 ),
    .din56_WIDTH( 16 ),
    .din57_WIDTH( 16 ),
    .din58_WIDTH( 16 ),
    .din59_WIDTH( 16 ),
    .din60_WIDTH( 16 ),
    .din61_WIDTH( 16 ),
    .din62_WIDTH( 16 ),
    .din63_WIDTH( 16 ),
    .din64_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mux_647_16_1_1_U606(
    .din0(trottersLocal_V_0_0_q0),
    .din1(trottersLocal_V_0_1_q0),
    .din2(trottersLocal_V_0_2_q0),
    .din3(trottersLocal_V_0_3_q0),
    .din4(trottersLocal_V_0_4_q0),
    .din5(trottersLocal_V_0_5_q0),
    .din6(trottersLocal_V_0_6_q0),
    .din7(trottersLocal_V_0_7_q0),
    .din8(trottersLocal_V_0_8_q0),
    .din9(trottersLocal_V_0_9_q0),
    .din10(trottersLocal_V_0_10_q0),
    .din11(trottersLocal_V_0_11_q0),
    .din12(trottersLocal_V_0_12_q0),
    .din13(trottersLocal_V_0_13_q0),
    .din14(trottersLocal_V_0_14_q0),
    .din15(trottersLocal_V_0_15_q0),
    .din16(trottersLocal_V_1_0_q0),
    .din17(trottersLocal_V_1_1_q0),
    .din18(trottersLocal_V_1_2_q0),
    .din19(trottersLocal_V_1_3_q0),
    .din20(trottersLocal_V_1_4_q0),
    .din21(trottersLocal_V_1_5_q0),
    .din22(trottersLocal_V_1_6_q0),
    .din23(trottersLocal_V_1_7_q0),
    .din24(trottersLocal_V_1_8_q0),
    .din25(trottersLocal_V_1_9_q0),
    .din26(trottersLocal_V_1_10_q0),
    .din27(trottersLocal_V_1_11_q0),
    .din28(trottersLocal_V_1_12_q0),
    .din29(trottersLocal_V_1_13_q0),
    .din30(trottersLocal_V_1_14_q0),
    .din31(trottersLocal_V_1_15_q0),
    .din32(trottersLocal_V_2_0_q0),
    .din33(trottersLocal_V_2_1_q0),
    .din34(trottersLocal_V_2_2_q0),
    .din35(trottersLocal_V_2_3_q0),
    .din36(trottersLocal_V_2_4_q0),
    .din37(trottersLocal_V_2_5_q0),
    .din38(trottersLocal_V_2_6_q0),
    .din39(trottersLocal_V_2_7_q0),
    .din40(trottersLocal_V_2_8_q0),
    .din41(trottersLocal_V_2_9_q0),
    .din42(trottersLocal_V_2_10_q0),
    .din43(trottersLocal_V_2_11_q0),
    .din44(trottersLocal_V_2_12_q0),
    .din45(trottersLocal_V_2_13_q0),
    .din46(trottersLocal_V_2_14_q0),
    .din47(trottersLocal_V_2_15_q0),
    .din48(trottersLocal_V_3_0_q0),
    .din49(trottersLocal_V_3_1_q0),
    .din50(trottersLocal_V_3_2_q0),
    .din51(trottersLocal_V_3_3_q0),
    .din52(trottersLocal_V_3_4_q0),
    .din53(trottersLocal_V_3_5_q0),
    .din54(trottersLocal_V_3_6_q0),
    .din55(trottersLocal_V_3_7_q0),
    .din56(trottersLocal_V_3_8_q0),
    .din57(trottersLocal_V_3_9_q0),
    .din58(trottersLocal_V_3_10_q0),
    .din59(trottersLocal_V_3_11_q0),
    .din60(trottersLocal_V_3_12_q0),
    .din61(trottersLocal_V_3_13_q0),
    .din62(trottersLocal_V_3_14_q0),
    .din63(trottersLocal_V_3_15_q0),
    .din64(tmp_3_fu_1287_p65),
    .dout(tmp_3_fu_1287_p66)
);

QuantumMonteCarloU50_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln302_fu_1099_p2 == 1'd0))) begin
            indvar_flatten7_fu_222 <= add_ln302_fu_1105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_222 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln302_fu_1099_p2 == 1'd0))) begin
            packOfst_fu_214 <= add_ln303_fu_1241_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            packOfst_fu_214 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_ln305_fu_210 <= 496'd0;
        end else if (((icmp_ln302_reg_1492 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_ln305_fu_210 <= select_ln305_fu_1447_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln302_fu_1099_p2 == 1'd0))) begin
            t_fu_218 <= select_ln302_2_fu_1137_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_218 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln302_reg_1492 <= icmp_ln302_fu_1099_p2;
        icmp_ln305_reg_1831_pp0_iter1_reg <= icmp_ln305_reg_1831;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln302_fu_1099_p2 == 1'd0))) begin
        icmp_ln303_reg_1496 <= icmp_ln303_fu_1117_p2;
        icmp_ln305_reg_1831 <= icmp_ln305_fu_1235_p2;
        trunc_ln302_reg_1501 <= trunc_ln302_fu_1145_p1;
        trunc_ln305_reg_1506 <= trunc_ln305_fu_1153_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln302_reg_1492 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln_reg_1841 <= or_ln_fu_1421_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln302_fu_1099_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln302_reg_1492 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_222;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_packOfst_load = 9'd0;
    end else begin
        ap_sig_allocacmp_packOfst_load = packOfst_fu_214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 3'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_218;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln305_reg_1831_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln305_reg_1831_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_0_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_10_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_11_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_12_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_13_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_14_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_15_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_1_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_2_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_3_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_4_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_5_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_6_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_7_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_8_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_0_9_ce0 = 1'b1;
    end else begin
        trottersLocal_V_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_0_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_10_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_11_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_12_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_13_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_14_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_15_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_1_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_2_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_3_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_4_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_5_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_6_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_7_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_8_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_1_9_ce0 = 1'b1;
    end else begin
        trottersLocal_V_1_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_0_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_10_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_11_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_12_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_13_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_14_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_15_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_1_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_2_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_3_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_4_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_5_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_6_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_7_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_8_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_2_9_ce0 = 1'b1;
    end else begin
        trottersLocal_V_2_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_0_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_10_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_11_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_12_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_13_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_14_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_15_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_1_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_2_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_3_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_4_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_5_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_6_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_7_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_8_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trottersLocal_V_3_9_ce0 = 1'b1;
    end else begin
        trottersLocal_V_3_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln302_1_fu_1131_p2 = (ap_sig_allocacmp_t_load + 3'd1);

assign add_ln302_fu_1105_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 11'd1);

assign add_ln303_fu_1241_p2 = (select_ln302_fu_1123_p3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((icmp_ln305_reg_1831_pp0_iter1_reg == 1'd1) & (m_axi_gmem_WREADY == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln302_fu_1099_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_1117_p2 = ((ap_sig_allocacmp_packOfst_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln305_fu_1235_p2 = ((trunc_ln303_fu_1149_p1 == 5'd31) ? 1'b1 : 1'b0);

assign lshr_ln_fu_1157_p4 = {{select_ln302_fu_1123_p3[7:4]}};

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = or_ln_reg_1841;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 64'd18446744073709551615;

assign m_axi_gmem_WUSER = 1'd0;

assign or_ln_fu_1421_p3 = {{tmp_3_fu_1287_p66}, {select_ln302_1_fu_1270_p3}};

assign select_ln302_1_fu_1270_p3 = ((icmp_ln303_reg_1496[0:0] == 1'b1) ? 496'd0 : phi_ln305_fu_210);

assign select_ln302_2_fu_1137_p3 = ((icmp_ln303_fu_1117_p2[0:0] == 1'b1) ? add_ln302_1_fu_1131_p2 : ap_sig_allocacmp_t_load);

assign select_ln302_fu_1123_p3 = ((icmp_ln303_fu_1117_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_packOfst_load);

assign select_ln305_fu_1447_p3 = ((icmp_ln305_reg_1831[0:0] == 1'b1) ? 496'd0 : tmp_6_fu_1439_p3);

assign tmp_1_fu_1429_p4 = {{select_ln302_1_fu_1270_p3[495:16]}};

assign tmp_2_fu_1277_p3 = {{trunc_ln302_reg_1501}, {trunc_ln305_reg_1506}};

assign tmp_3_fu_1287_p65 = tmp_2_fu_1277_p3;

assign tmp_6_fu_1439_p3 = {{tmp_3_fu_1287_p66}, {tmp_1_fu_1429_p4}};

assign trottersLocal_V_0_0_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_10_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_11_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_12_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_13_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_14_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_15_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_1_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_2_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_3_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_4_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_5_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_6_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_7_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_8_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_0_9_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_0_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_10_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_11_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_12_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_13_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_14_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_15_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_1_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_2_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_3_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_4_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_5_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_6_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_7_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_8_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_1_9_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_0_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_10_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_11_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_12_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_13_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_14_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_15_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_1_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_2_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_3_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_4_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_5_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_6_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_7_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_8_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_2_9_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_0_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_10_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_11_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_12_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_13_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_14_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_15_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_1_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_2_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_3_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_4_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_5_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_6_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_7_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_8_address0 = zext_ln305_fu_1167_p1;

assign trottersLocal_V_3_9_address0 = zext_ln305_fu_1167_p1;

assign trunc_ln302_fu_1145_p1 = select_ln302_2_fu_1137_p3[1:0];

assign trunc_ln303_fu_1149_p1 = select_ln302_fu_1123_p3[4:0];

assign trunc_ln305_fu_1153_p1 = select_ln302_fu_1123_p3[3:0];

assign zext_ln305_fu_1167_p1 = lshr_ln_fu_1157_p4;

endmodule //QuantumMonteCarloU50_QuantumMonteCarloU50_Pipeline_WRITE_TROTTERS_VITIS_LOOP_303_6
