-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity QuantumMonteCarloU50_copysignf is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of QuantumMonteCarloU50_copysignf is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal data_V_fu_14_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln368_fu_18_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_s_fu_22_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= p_Result_s_fu_22_p3;
    data_V_fu_14_p1 <= x;
    p_Result_s_fu_22_p3 <= (ap_const_lv1_1 & trunc_ln368_fu_18_p1);
    trunc_ln368_fu_18_p1 <= data_V_fu_14_p1(31 - 1 downto 0);
end behav;
